### PR TITLE
Windows openSCAD detection and color output fix

### PR DESCRIPTION
**Pull request by csamid**
## What
This pull request:
1) enables OpenSCAD detection on Windows
2) resolves a color output inconsistency issue on Windows consoles.
## Why
1) OpenSCAD detection was not available on Windows systems.
2) OpenSCAD detection changes introduced a color output  inconsistencies on Windows consoles.
### OpenSCAD Detection
I replaced `os.system()` with `subprocess.run()` for executing `openscad -v`
### Colorama Solution
Calls `just_fix_windows_console()` function from the `colorama` library to address the color output inconsistency. 
## Visual Demos
Screenshots below illustrate the impact of the changes. These showcase code output comparisons before and after the modifications. It covers both Windows and Linux environments while OpenSCAD is installed
### Before and After Screenshots
1. [Windows Before - Unable to detect](https://github.com/Rhoban/onshape-to-robot/assets/85626643/e6d71e38-992b-4924-83fa-41fb77a73b0b)
2. [Windows After 1. - Color output inconsistency](https://github.com/Rhoban/onshape-to-robot/assets/85626643/a2072aaa-2920-4b5a-b877-48c078e9cd07)
3. [Windows After 1. and 2. - Consistent color output](https://github.com/Rhoban/onshape-to-robot/assets/85626643/85dc4681-4300-4f19-b014-42de2e8c414d)
4. [Linux (wsl2) Before - Works](https://github.com/Rhoban/onshape-to-robot/assets/85626643/b7e1d16a-9e18-4528-a5b1-aaabba83d4c6)
5. [Linux (wsl2) After - Still works](https://github.com/Rhoban/onshape-to-robot/assets/85626643/056317ba-e657-44c0-82e0-e69c7a883aa6)

### CODE REVIEW

**Comment by Gregwar** [comment]
Hello,

Seems good to me, only we know to update `requirements.txt` and `setup.py` to depend on `colorama >= 0.4.6` which includes `just_fix_window_console`. I will merge, do it and repackage

**Comment by Gregwar** [comment]
Updated dependency and uploaded upstream `v0.3.20`

**Comment by Gregwar** [comment]
Can you confirm me it's working ?

**Comment by csamid** [comment]
It works!

**Pull request merged**
