### PR TITLE
Update setup.py to use entry_points

### PR DESCRIPTION
**Pull request by rsinnet**
Use the entry_points options to auto-generate CLI entrypoint scripts.
These scripts are generated by the installer so they take into account
the system's environment and thus are more robust.

### CODE REVIEW

**Comment by Gregwar** [comment]
Hello,

Thanks for your suggestion
If we go this way I think we should also make `clear-cache` uniform with the rest, would you mind updating PR ?

**Comment by rsinnet** [comment]
@Gregwar addressed your comments FYI.

**Comment by Gregwar** [comment]
Sounds good, thanks for contributing

**Comment by Gregwar** [comment]
I will publish a new version anytime soon

**Pull request merged**
