### PR TITLE
fix problems with long configuration names (a bit hacky)

### PR DESCRIPTION
**Pull request by SammyRamone**
Standard library parts (screws, nuts, etc) often have extremely long configuration names. This leads to errors when saving the STL because the file name is too long.
This PR fixes this a bit hacky by shortening the number of chars in the configuration name

### CODE REVIEW

**Comment by Gregwar** [comment]
I think we might have collisions if we do that, maybe we can test the length instead, and if it's longer than N (like 40) use some hash instead of the configuration itself

I am afraid that long strings will be like:
```
a=1,b=2,c=3,d=4...
```

And if we just cut we will have different configurations with same part name

What do you think?

**Comment by SammyRamone** [comment]
for my project it looked like there were no collisions. The configuration strings seem very random. But never the less you are right, using a hash is the less hacky way to do it.
I will change that

**Comment by Gregwar** [comment]
Ok, waiting for you to ping me then
Are you working in Gazebo?

**Comment by SammyRamone** [comment]
I committed a change to use a hash for longer names. I leave the short names like they are, so it is more readable
Currently I only tested the model in RViz. But generally we are using Gazebo for automatic parameter search (https://github.com/bit-bots/parallel_parameter_search) and general testing. I'm also using PyBullet for reinforcement learning
I hope that I will be able to test it also in Gazebo and PyBullet this week

**Pull request merged**
