### PR TITLE
Add instructions for using debugpy

### PR DESCRIPTION
**Pull request by rsinnet**
Add debugging instructions for developers.

### CODE REVIEW

**Comment by Gregwar** [comment]
I think we should mention the `requirements.txt` that is needed when we don't use the python wheel here.

However, I am not sure explaining how to use debugging with Python is relevant for this project, maybe we can simply link to an external tutorial since I think this is very common and general ?

**Comment by rsinnet** [comment]
> I think we should mention the `requirements.txt` that is needed when we don't use the python wheel here.
> 
> However, I am not sure explaining how to use debugging with Python is relevant for this project, maybe we can simply link to an external tutorial since I think this is very common and general ?

That sounds fine to me. I can close this PR.

**Comment by Gregwar** [comment]
I think a development section on the doc is a good idea though, where we explain how to setup the tool using `requirements.txt` instead of setup.py and using the modules instead of entry points

**Comment by Gregwar** [comment]
Will you open another PR or may I write something about that in the documentation ?

**Pull request closed without merging**
