### PR TITLE
Fix entrypoint scripts and cache path on some environments

### PR DESCRIPTION
**Pull request by rsinnet**
It looks like a lot of lines, but really it's mostly indenting code in scripts
to avoid unexpected side effects when importing modules.

Modify script modules such that functionality is wrapped in a function
call. This prevents unexpected behavior when importing a module. This
also fixes an issue I had installing and running these entrypoints on
a different environment than I had previously tested on.

Also move the cache path from the location of the onshape_api module to
the user's home directory. This handles environments where the package
is installed globally, in which case the previous cache directory
location is not generally writeable by the user.

**Note that this PR includes https://github.com/Rhoban/onshape-to-robot/issues/64, so that should be merged first, or this PR can be adapted if the previous PR is not wanted.**

See also: https://github.com/Rhoban/onshape-to-robot/issues/63
See also: https://github.com/Rhoban/onshape-to-robot/issues/64

### CODE REVIEW

**Comment by rsinnet** [comment]
@Gregwar I tested to the extent that I am familiar with the functionality, but I don't have a complete list of test cases to run through.

I ran the exporter against the examples repo: https://github.com/Rhoban/onshape-to-robot-examples

And I tested the other scripts like clearing cache and editing shapes. It seems to work but it's totally possible that I missed some piece of functionality in testing, so I defer to you for proper testing procedures.

Overall, this PR should make the code run more consistently across environments, particularly user vs. global install.

**Comment by Gregwar** [comment]
Looks like #64 is included in this as well, can you confirm?
In that case close #64 and I will review this one as a whole.

This PR is indeed important since it fixes the current issue with entry points (in development mode we don't use them that is why I didn't notice at first glance).

It is true that we lack automated tests here, but I am not sure those are possible to setup without making an Onshape API key public, I will investigate someday but currently my schedule is very tight.

**Comment by rsinnet** [comment]
> Looks like #64 is included in this as well, can you confirm? In that case close #64 and I will review this one as a whole.
> 
> This PR is indeed important since it fixes the current issue with entry points (in development mode we don't use them that is why I didn't notice at first glance).
> 
> It is true that we lack automated tests here, but I am not sure those are possible to setup without making an Onshape API key public, I will investigate someday but currently my schedule is very tight.

I went ahead and closed #64.

I agree it is challenging due to lack of tests. Fortunately it's quick enough to test manually. One thought would be to use the mock package to mock the Onshape API. Of course, this is a good bit of work, so I wouldn't expect you to have the time there.

Thanks a bunch for the quick response and for keeping up the code. It's tough to maintain open-source.

**Comment by Gregwar** [comment]
Thanks for contributing!

**Comment by Gregwar** [comment]
One comment: `pybullet` is imported even when we don't use it (while importing models), I think that could be avoided

**Pull request merged**
