### PR TITLE
Joint Limits for Revolute Joints

### PR DESCRIPTION
**Pull request by SammyRamone**
Hi,
first thanks for creating this very helpful piece of software!
I did some additions that were necessary to make it usable for us. I will create separate PRs for it and you can decide if you want to merge them upstream.
This PR adds limits to revolute joints based on what is specified in the assembly

### CODE REVIEW

**Comment by Gregwar** [comment]
Hi Marc,
I guess this address #22 

A few comments:
* I think limits should be optionals, since you can totally ignore them in both onshape and URDF models
* Limits in prismatic should be handled too

If you want I can merge and fix that

**Comment by SammyRamone** [comment]
I think you mean https://github.com/Rhoban/onshape-to-robot/issues/2 but yes.
Good point, limits should be optional by config option. I just kind of implemented what was missing for my own use case.
Yes, go ahead. I will pull your changes then downstream.
Thanks

**Comment by Gregwar** [comment]
Ok I will have a look
By optional I meant that if there is no limit in onshape, it should result in no limits in URDF/SDF as well

**Comment by Gregwar** [comment]
Thanks for contributing

**Comment by SammyRamone** [comment]
> Ok I will have a look
> By optional I meant that if there is no limit in onshape, it should result in no limits in URDF/SDF as well

okay that would work too

**Comment by Gregwar** [comment]
It's done, I am also reading the values for prismatic, and if the "limits" box is not ticked I don't use any
However I don't like that much the code because it looks like it depends on the unit system that the user is using

**Comment by SammyRamone** [comment]
I tried setting my units on rad and setting the limits in rad for one joint. It looks like it's given me the number in degree anyway. Therefore this should not be a problem

**Comment by Gregwar** [comment]
Actually I guess it depends on your workspace settings and not on the unit you typed the expression.. anyway let's keep it as is for now

**Pull request merged**
