### PR TITLE
ROS support

### PR DESCRIPTION
**Pull request by SammyRamone**
This adds support for ROS users by adding 3 more config options (see Readme)

### CODE REVIEW

**Comment by Gregwar** [comment]
Hi,
I don't see a change in `config.py`, while you add some settings I think something is missing, isn't it?

**Comment by SammyRamone** [comment]
correct, I committed the missing file

**Comment by Gregwar** [comment]
Ok sounds good to me

**Comment by Gregwar** [comment]
Ok apparently this broke master
Are you sure this PR was ok?

**Comment by Gregwar** [comment]
What is supposed to be `addDummyBaseLink` ? A boolean or a metho ? :smile:

**Comment by Gregwar** [comment]
And is this dummy base link only required for URDFs ?

**Comment by SammyRamone** [comment]
ah damn, that whats happens when you do a last second clean up before creating a PR and not testing, sorry
I will fix it
I'm only using URDF, so I'm not sure if it is also needed for SDF, but propably

**Pull request merged**
